backend:
  name: git-gateway
  branch: main

local_backend: true
# change url to a link to the image you want to use, no file paths, must be a URL
logo_url: http://localhost:8080/assets/images/JCBTC.jpg

media_folder: 'public/images/blog'
public_folder: '/images/blog'

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/blog'
    create: true
    slug: '{{pageName}}'
    fields:
      - { label: 'Published', name: 'published', widget: 'boolean', default: true, hint: 'Check to publish the blog post.' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Tags', name: 'tags', widget: 'list', default: ['blog'] }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }


  - name: 'events'
    label: 'Events'
    folder: 'src/events'
    create: true
    slug: '{{pageName}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime' }
      - { label: 'Tags', name: 'tags', widget: 'list', default: ['event'] }
      - { label: 'Meetup Link', name: 'meetupLink', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
