backend:
  name: git-gateway
  branch: main

local_backend: true
# change url to a link to the image you want to use, no file paths, must be a URL
logo_url: https://jerseycitybitcoin.netlify.app/assets/images/JCBTC.png

media_folder: 'public/images/blog'
public_folder: '/images/blog'

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/blog'
    create: true
    slug: '{{pageName}}'
    fields:
      - { label: 'Published', name: 'published', widget: 'boolean', default: true, hint: 'Check to publish the blog post.', required: true }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Date', name: 'date', widget: 'datetime', required: true }
      - { label: 'Tags', name: 'tags', widget: 'list', default: ['blog'], required: true }
      - { label: 'Author', name: 'author', widget: 'string', required: true }
      - { label: 'Author Link', name: 'authorLink', widget: 'string', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }

  - name: 'events'
    label: 'Events'
    folder: 'src/events'
    create: true
    slug: '{{pageName}}'
    fields:
      - { label: 'Published', name: 'published', widget: 'boolean', default: true, hint: 'Check to publish the blog post.', required: true }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Date', name: 'date', widget: 'datetime', required: true }
      - { label: 'Tags', name: 'tags', widget: 'list', default: ['event'] }
      - { label: 'Meetup Link', name: 'meetup', widget: 'string', required: true }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
      - { label: 'Type', name: 'type', widget: 'string', required: true }